import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Terms of Service — IntellaBets",
}

export default function TermsPage() {
  const updated = "April 18, 2026"
  return (
    <div className="max-w-3xl mx-auto py-10 space-y-8 text-gray-300 text-sm leading-relaxed">
      <div>
        <h1 className="text-3xl font-black text-white mb-2">Terms of Service</h1>
        <p className="text-gray-500">Last updated: {updated}</p>
      </div>

      <div className="p-4 rounded-lg bg-yellow-500/10 border border-yellow-500/20 text-yellow-300 text-sm">
        <strong>Important:</strong> IntellaBets provides sports analytics and tipster picks for informational
        and entertainment purposes only. We are not a sportsbook, do not accept bets, and are not responsible
        for any wagering decisions you make. Please gamble responsibly.
      </div>

      <section className="space-y-3">
        <h2 className="text-lg font-bold text-white">1. Eligibility</h2>
        <p>
          You must be at least 18 years old (or the legal gambling age in your jurisdiction, whichever is
          higher) to use IntellaBets. By accessing the platform you confirm you meet this requirement.
          You are solely responsible for complying with all laws in your jurisdiction regarding sports
          betting and online wagering services.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-bold text-white">2. Accounts</h2>
        <ul className="list-disc list-inside space-y-2 ml-2">
          <li>You are responsible for all activity under your account.</li>
          <li>You must provide accurate registration information.</li>
          <li>One account per person. Multi-accounting to abuse promotions is prohibited.</li>
          <li>You must keep your login credentials confidential.</li>
          <li>We may suspend or terminate accounts that violate these Terms.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-bold text-white">3. Subscriptions &amp; Billing</h2>
        <ul className="list-disc list-inside space-y-2 ml-2">
          <li><strong className="text-white">Premium Tipster ($19.99/mo):</strong> Grants the ability to publish betslips and earn from subscribers. Billed monthly. Cancel anytime.</li>
          <li><strong className="text-white">AI Picks ($9.99/mo):</strong> Grants access to Claude-powered betslip generation. Billed monthly. Cancel anytime.</li>
          <li><strong className="text-white">Tipster Subscriptions ($4.99–$49.99/mo):</strong> Access to a specific tipster&apos;s picks. Billed monthly. Cancel anytime via your account settings.</li>
          <li>Subscriptions auto-renew monthly until cancelled.</li>
          <li>On web, payments are processed by Stripe. On iOS, by Apple. On Android, by Google. Refund policies are subject to those providers&apos; terms.</li>
          <li>We may change prices with 30 days&apos; notice.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-bold text-white">4. Tipster Revenue Share</h2>
        <ul className="list-disc list-inside space-y-2 ml-2">
          <li>Premium Tipsters earn 80% of each subscriber payment; IntellaBets retains 20% as a platform service fee.</li>
          <li>Payouts are issued monthly to the tipster&apos;s registered payout method, subject to a minimum threshold.</li>
          <li>IntellaBets may withhold payouts if we suspect fraudulent activity or Terms violations pending investigation.</li>
          <li>Tipsters are responsible for reporting and paying any applicable taxes on earnings.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-bold text-white">5. Content Standards</h2>
        <p>When publishing betslips or other content you agree not to:</p>
        <ul className="list-disc list-inside space-y-2 ml-2">
          <li>Post false, misleading, or manipulated performance records.</li>
          <li>Guarantee winnings or misrepresent past results.</li>
          <li>Infringe intellectual property rights.</li>
          <li>Post spam, malware, or abusive content.</li>
          <li>Impersonate other users or public figures.</li>
        </ul>
        <p>We may remove content that violates these standards without notice.</p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-bold text-white">6. Disclaimer of Warranties</h2>
        <p>
          IntellaBets is provided &quot;as is&quot; without warranties of any kind. We do not guarantee the accuracy,
          completeness, or profitability of any picks, predictions, or analytics provided on the platform
          — including those generated by AI. Past performance of any tipster does not guarantee future results.
          Sports betting involves risk; you may lose money.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-bold text-white">7. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, IntellaBets and its officers, employees, and affiliates
          are not liable for any direct, indirect, incidental, or consequential damages arising from your
          use of the platform, including wagering losses incurred based on picks or predictions viewed here.
          Our total liability to you for any claim shall not exceed the amount you paid us in the 3 months
          preceding the claim.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-bold text-white">8. Responsible Gambling</h2>
        <p>
          IntellaBets promotes responsible gambling. If you or someone you know has a gambling problem,
          please seek help:
        </p>
        <ul className="list-disc list-inside space-y-1 ml-2">
          <li>National Council on Problem Gambling: <a href="https://www.ncpgambling.org" target="_blank" rel="noopener noreferrer" className="text-purple-400 hover:underline">ncpgambling.org</a> / 1-800-522-4700</li>
          <li>Gamblers Anonymous: <a href="https://www.gamblersanonymous.org" target="_blank" rel="noopener noreferrer" className="text-purple-400 hover:underline">gamblersanonymous.org</a></li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-bold text-white">9. Termination</h2>
        <p>
          We may suspend or terminate your account at any time for violations of these Terms. You may close
          your account at any time from your account settings. Upon termination, active subscriptions will
          not be refunded for the current billing period.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-bold text-white">10. Governing Law</h2>
        <p>
          These Terms are governed by the laws of the State of Delaware, United States, without regard to
          conflict-of-law principles. Disputes shall be resolved by binding arbitration under AAA rules.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-bold text-white">11. Changes</h2>
        <p>
          We may revise these Terms at any time. We will notify you of material changes by email or in-app
          notice. Continued use after the effective date constitutes acceptance of the updated Terms.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-bold text-white">12. Contact</h2>
        <p>
          Questions about these Terms? Email{" "}
          <a href="mailto:support@intellabets.com" className="text-purple-400 hover:underline">
            support@intellabets.com
          </a>
        </p>
      </section>
    </div>
  )
}
